### ISSUE TITLE
[feature] add dbd grammar 

### ISSUE THREAD

**Issue by wtup** [epics-extensions/tree-sitter-epics#18]
It would be awesome if the parser included dbd grammar parsing.
[DBD SYNTAX SUMMARY](https://docs.epics-controls.org/en/latest/appdevguide/databaseDefinition.html):

```

path "path"
addpath "path"
include "filename"
#comment
menu(name) {
    include "filename" choice(choice_name, "choice_value")
    ...
}

recordtype(record_type) {}

recordtype(record_type) {
    include "filename"
    field(field_name, field_type) {
        asl(asl_level)
        initial("init_value")
        promptgroup("group_name")
        prompt("prompt_value")
        special(special_value)
        pp(pp_value)
        interest(interest_level)
        base(base_type)
        size(size_value)
        extra("extra_info")
        menu(name)
        prop(yesno)
    }
    %C_declaration
    ...
}

device(record_type, link_type, dset_name, "choice_string")

driver(drvet_name)

registrar(function_name)

variable(variable_name)

breaktable(name) {
    raw_value eng_value
    ...
}
```

**Comment by minijackson** [comment]
Hey there!

tree-sitter-epics already supports the dbd grammar. You can see this for example in the epics-db's declarations test: https://github.com/epics-extensions/tree-sitter-epics/blob/master/epics-db/test/corpus/declarations.txt

The `.db` and `.dbd` grammar are both implemented in `epics-db`, since from the point of view of epics-base, it's the same syntax. See [here](https://github.com/epics-base/epics-base/blob/7.0/modules/database/src/ioc/dbStatic/dbYacc.y#L59-L60) for example, where epics-base can parse both a `record(...){}` and a `breaktable(...){}`

**Comment by wtup** [comment]
Hi, yeah I have assumed the `epics-db` grammar did not support `dbd` parsing, before checking the source. Sorry for bothering you!

**Comment by minijackson** [comment]
No worries!
